export interface MandiConfig {
  id: string;
  name: string;
  name_mr: string;
  name_hi: string;
  lat: number;
  lng: number;
  taluka: string;
  baseArrivalsQuintalPerDay: number;
  specialtyCrop: 'onion' | 'tomato' | 'soybean' | 'all';
}

export const MANDIS: MandiConfig[] = [
  {
    id: 'lasalgaon',
    name: 'Lasalgaon APMC',
    name_mr: 'लासलगाव कृषी उत्पन्न बाजार समिती',
    name_hi: 'लासलगांव मंडी',
    lat: 20.1472,
    lng: 74.2262,
    taluka: 'Niphad',
    baseArrivalsQuintalPerDay: 45000,
    specialtyCrop: 'onion',
  },
  {
    id: 'pimpalgaon',
    name: 'Pimpalgaon Baswant APMC',
    name_mr: 'पिंपळगाव बसवंत बाजार समिती',
    name_hi: 'पिंपलगांव बसवंत मंडी',
    lat: 20.1706,
    lng: 73.9856,
    taluka: 'Niphad',
    baseArrivalsQuintalPerDay: 38000,
    specialtyCrop: 'tomato',
  },
  {
    id: 'nashik',
    name: 'Nashik (Panchavati) APMC',
    name_mr: 'नाशिक (पंचवटी) बाजार समिती',
    name_hi: 'नासिक मंडी',
    lat: 20.0110,
    lng: 73.7903,
    taluka: 'Nashik',
    baseArrivalsQuintalPerDay: 25000,
    specialtyCrop: 'all',
  },
  {
    id: 'yeola',
    name: 'Yeola APMC',
    name_mr: 'येवला बाजार समिती',
    name_hi: 'येवला मंडी',
    lat: 20.0382,
    lng: 74.4891,
    taluka: 'Yeola',
    baseArrivalsQuintalPerDay: 18000,
    specialtyCrop: 'onion',
  },
  {
    id: 'manmad',
    name: 'Manmad APMC',
    name_mr: 'मनमाड बाजार समिती',
    name_hi: 'मनमाड मंडी',
    lat: 20.2508,
    lng: 74.4394,
    taluka: 'Nandgaon',
    baseArrivalsQuintalPerDay: 12000,
    specialtyCrop: 'soybean',
  },
  {
    id: 'sinnar',
    name: 'Sinnar APMC',
    name_mr: 'सिन्नर बाजार समिती',
    name_hi: 'सिन्नर मंडी',
    lat: 19.8510,
    lng: 73.9930,
    taluka: 'Sinnar',
    baseArrivalsQuintalPerDay: 16000,
    specialtyCrop: 'all',
  },
  {
    id: 'dindori',
    name: 'Dindori APMC',
    name_mr: 'दिंडोरी बाजार समिती',
    name_hi: 'दिंडोरी मंडी',
    lat: 20.2014,
    lng: 73.8340,
    taluka: 'Dindori',
    baseArrivalsQuintalPerDay: 15000,
    specialtyCrop: 'tomato',
  },
  {
    id: 'niphad',
    name: 'Niphad APMC',
    name_mr: 'निफाड बाजार समिती',
    name_hi: 'निफाड़ मंडी',
    lat: 20.0898,
    lng: 74.1082,
    taluka: 'Niphad',
    baseArrivalsQuintalPerDay: 20000,
    specialtyCrop: 'onion',
  },
  {
    id: 'chandwad',
    name: 'Chandwad APMC',
    name_mr: 'चांदवड बाजार समिती',
    name_hi: 'चांदवड़ मंडी',
    lat: 20.3275,
    lng: 74.2407,
    taluka: 'Chandwad',
    baseArrivalsQuintalPerDay: 14000,
    specialtyCrop: 'onion',
  },
  {
    id: 'malegaon',
    name: 'Malegaon APMC',
    name_mr: 'मालेगाव बाजार समिती',
    name_hi: 'मालेगांव मंडी',
    lat: 20.5539,
    lng: 74.5288,
    taluka: 'Malegaon',
    baseArrivalsQuintalPerDay: 28000,
    specialtyCrop: 'soybean',
  },
  {
    id: 'satana',
    name: 'Satana (Baglan) APMC',
    name_mr: 'सटाणा (बागलाण) बाजार समिती',
    name_hi: 'सटाणा मंडी',
    lat: 20.5912,
    lng: 74.2045,
    taluka: 'Baglan',
    baseArrivalsQuintalPerDay: 22000,
    specialtyCrop: 'onion',
  },
  {
    id: 'nandgaon',
    name: 'Nandgaon APMC',
    name_mr: 'नांदगाव बाजार समिती',
    name_hi: 'नांदगांव मंडी',
    lat: 20.3128,
    lng: 74.6593,
    taluka: 'Nandgaon',
    baseArrivalsQuintalPerDay: 10000,
    specialtyCrop: 'soybean',
  },
  {
    id: 'kalwan',
    name: 'Kalwan APMC',
    name_mr: 'कळवण बाजार समिती',
    name_hi: 'कलवण मंडी',
    lat: 20.4905,
    lng: 73.9972,
    taluka: 'Kalwan',
    baseArrivalsQuintalPerDay: 13000,
    specialtyCrop: 'onion',
  },
  {
    id: 'igatpuri',
    name: 'Igatpuri (Ghoti) APMC',
    name_mr: 'इगतपुरी (घोटील) बाजार समिती',
    name_hi: 'इगतपुरी (घोटी) मंडी',
    lat: 19.7027,
    lng: 73.5583,
    taluka: 'Igatpuri',
    baseArrivalsQuintalPerDay: 8000,
    specialtyCrop: 'all',
  },
];
